# Generated by Django 3.1.4 on 2020-12-15 18:04

from django.db import migrations, models
import django_enum_choices.choice_builders
import django_enum_choices.fields
import notifications.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('send_data', models.DateTimeField()),
                ('comunication_type', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Email', 'Email'), ('Sms', 'Sms'), ('Push', 'Push'), ('Whatsapp', 'Whatsapp')], enum_class=notifications.models.comunication_type, max_length=8)),
                ('send_status', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Sent', 'Sent'), ('Error', 'Error'), ('Waiting', 'Waiting')], enum_class=notifications.models.send_status, max_length=7)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('receiver', models.CharField(max_length=150)),
                ('name_receiver', models.CharField(max_length=100)),
            ],
        ),
    ]
